apiVersion: v2
name: pagopa-payment-options
description: Microservice that handles services for payment options
type: application
version: 0.122.0
appVersion: 0.11.0-3-PIDM-1485-service-crash-loop-backoff
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
