apiVersion: v2
name: pagopa-payment-options
description: Microservice that handles services for payment options
type: application
version: 0.116.0
appVersion: 0.9.4
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
