apiVersion: v2
name: pagopa-payment-options
description: Microservice that handles services for payment options
type: application
version: 0.114.0
appVersion: 0.9.2
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
